[2024-03-18T20:44:07.428+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.Options_Crawler manual__2024-03-18T20:44:04.748046+00:00 [queued]>
[2024-03-18T20:44:07.433+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.Options_Crawler manual__2024-03-18T20:44:04.748046+00:00 [queued]>
[2024-03-18T20:44:07.434+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-18T20:44:07.443+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Options_Crawler> on 2024-03-18 20:44:04.748046+00:00
[2024-03-18T20:44:07.448+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-03-18T20:44:07.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Options_Crawler', 'manual__2024-03-18T20:44:04.748046+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/crawler.py', '--cfg-path', '/tmp/tmpht93x__u']
[2024-03-18T20:44:07.453+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask Options_Crawler
[2024-03-18T20:44:07.492+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.Options_Crawler manual__2024-03-18T20:44:04.748046+00:00 [running]> on host 4af0b55fad3c
[2024-03-18T20:44:07.555+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='Options_Crawler' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T20:44:04.748046+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T20:44:04.748046+00:00'
[2024-03-18T20:44:42.665+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-18T20:44:42.665+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS mongo-database:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65f8a79cb68fb0ad9e1d5a54, topology_type: Unknown, servers: [<ServerDescription ('mongo-database', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo-database:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-03-18T20:44:42.669+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-18T20:44:42.681+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Options_Crawler, execution_date=20240318T204404, start_date=20240318T204407, end_date=20240318T204442
[2024-03-18T20:44:42.710+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-18T20:44:42.732+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
