[2024-03-18T20:32:28.514+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.Options_Crawler manual__2024-03-18T20:32:27.262256+00:00 [queued]>
[2024-03-18T20:32:28.522+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.Options_Crawler manual__2024-03-18T20:32:27.262256+00:00 [queued]>
[2024-03-18T20:32:28.523+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-18T20:32:28.532+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): Options_Crawler> on 2024-03-18 20:32:27.262256+00:00
[2024-03-18T20:32:28.537+0000] {standard_task_runner.py:60} INFO - Started process 258 to run task
[2024-03-18T20:32:28.541+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Options_Crawler', 'manual__2024-03-18T20:32:27.262256+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/crawler.py', '--cfg-path', '/tmp/tmp88z3c719']
[2024-03-18T20:32:28.543+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask Options_Crawler
[2024-03-18T20:32:28.581+0000] {task_command.py:423} INFO - Running <TaskInstance: my_dag.Options_Crawler manual__2024-03-18T20:32:27.262256+00:00 [running]> on host 65bb8df62808
[2024-03-18T20:32:28.644+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='Options_Crawler' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T20:32:27.262256+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T20:32:27.262256+00:00'
[2024-03-18T20:33:00.706+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-18T20:33:00.707+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS mongo-database:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65f8a4deea6e208851aa3d26, topology_type: Unknown, servers: [<ServerDescription ('mongo-database', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo-database:27017: [Errno -2] Name or service not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-03-18T20:33:00.710+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-18T20:33:00.720+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Options_Crawler, execution_date=20240318T203227, start_date=20240318T203228, end_date=20240318T203300
[2024-03-18T20:33:00.755+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-18T20:33:00.771+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
