[2024-03-18T23:35:30.233+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: my_dag.Options_Crawler manual__2024-03-18T23:34:57.100699+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
